name: CI/CD Pipeline for Azure MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pymysql mysql-connector-python

      - name: Database Operations
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/table_creation.sql
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/schema_update.sql
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/data_seed.sql

      - name: Run Concurrent Queries
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python scripts/multi_thread_queries.py
